=== OpenAlcoholics/drinking-game-cards/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "drinking-game-cards",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "text",
            "count",
            "uses",
            "rounds",
            "personal",
            "remote",
            "unique",
            "id"
        ],
        "properties": {
            "text": {
                "type": "string",
                "minLength": 1,
                "description": "The task text. It may contain {int} as a placeholder for a random number."
            },
            "count": {
                "type": "integer",
                "minimum": 1,
                "description": "How many times the card can occur in one session -> implicit higher probability"
            },
            "uses": {
                "type": "integer",
                "minimum": 0,
                "description": "How often the (interactive) card can be used."
            },
            "rounds": {
                "type": "integer",
                "minimum": -1,
                "description": "How many rounds the card is active for. If uses > 1, the rounds are counted after each use. Use -1 for infinite duration."
            },
            "id": {
                "type": "integer",
                "description": "The ID of this task. Note that this is NOT always the index in the tasks list."
            },
            "personal": {
                "type": "boolean",
                "description": "Whether the task is for a specific player or the whole group."
            },
            "remote": {
                "type": "boolean",
                "description": "Whether this task can be used in a remote game (i.e. not all players are in the same room)."
            },
            "unique": {
                "type": "boolean",
                "description": "Whether only one instance of this task can be active (rounds != 0 && count > 1). The latest card replaces previous ones."
            }
        }
    }
}

=== OpenAlcoholics/drinking-game-cards/tasks_en.json
[{"text": "Drink {int} times if you've ever worked under the table.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 0}, {"text": "Drink {int} times if you've ever borrowed money from your partner without telling him or her.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 1}, {"text": "Drink {int} times if you've ever lied about the size of your penis or your partner's.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 2}, {"text": "Drink {int} times if you've ever been pulled over by the police.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 3}, {"text": "Drink {int} times if you've ever been taken into custody.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 4}, {"text": "Drink {int} times if you've ever tried on your partner's underwear.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 5}, {"text": "Drink {int} times if you're a girl and you've used your boyfriend's pants or his tshirt as pajamas.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 6}, {"text": "Drink {int} times if you would fck someone for , dollars, while he or she is in good health.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 7}, {"text": "Drink {int} times if you had erotic dreams this week efault.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 8}, {"text": "Drink {int} times if you've ever seen one of the other players naked efault.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 9}, {"text": "Drink {int} times if you've ever fcked at work ult.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 10}, {"text": "Drink {int} times if you've ever gotten drunk alone.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 11}, {"text": "Drink {int} times if you sleep like sht after sex.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 12}, {"text": "Drink {int} times if the last movie you saw was romantic lt.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 13}, {"text": "Drink {int} times if the last film you saw is American ault.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 14}, {"text": "Drink {int} times if you've ever measured your penis or your partner's penis efault.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 15}, {"text": "Drink {int} times if you've ever woken up in someone's bed with no idea how you got there.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 16}, {"text": "Drink {int} times if you've ever made love in water.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 17}, {"text": "Drink {int} times if you say I love you to your boyfriendgirlfriend at the end of every phone call or almost.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 18}, {"text": "Aholes who have asked can I have a bite when someone takes out a sandwich, you drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 19}, {"text": "If you've ever searched for something that is in your pocket, drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 20}, {"text": "If you've ever used a color pen with all four colors at the same time, drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 21}, {"text": "Drink {int} times if you've ever tried to fill a washcloth with water.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 22}, {"text": "Drink {int} times if you've ever waved your cell phone high in the air when you didn't have network.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 23}, {"text": "The player who dated the worst girl ever, drinks {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 24}, {"text": "The player who dated the worst guy ever, drinks {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 25}, {"text": "Drink {int} times if you've popped someone's cherry.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 26}, {"text": "If you've ever fcked a minor though you were major, drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 27}, {"text": "Drink {int} times if you think leggings are pants.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 28}, {"text": "drink as many sips as your number of sex partners.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 29}, {"text": "Brainiacs who skipped a year in school, drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 30}, {"text": "Sharks who study or work in finance or accounting, drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 31}, {"text": "Geeks who study or work in computer science, drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 32}, {"text": "Moneymakers who study or work in sales, drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 33}, {"text": "If you are starting to bald, drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 34}, {"text": "Drink {int} times if you have your coffee cigarette poop ritual at least every two days.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 35}, {"text": "Drink {int} times if you're a hunter.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 36}, {"text": "Drink {int} times if you've ever had several fck buddies at the same time.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 37}, {"text": "Drink {int} times if you've ever been cheated on.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 38}, {"text": "Drink {int} times if your shoes have shoelaces.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 39}, {"text": "The girl with the biggest boobs can give out {int} sips.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 40}, {"text": "The guy with the least amount of body hair drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 41}, {"text": "The person with the biggest nose drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 42}, {"text": "Give out {int} sips if your shoe size is more than . for UK.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 43}, {"text": "Give out {int} sips if your shoe size is less than for UK.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 44}, {"text": "Drink {int} times if your shoe size is between and . and . for UK.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 45}, {"text": "Give out {int} sips if your socks are white.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 46}, {"text": "Give out {int} sips if you haven't seen any of the Star Wars movies.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 47}, {"text": "TheThe Rings movies.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 48}, {"text": "Give out {int} sips if you haven't seen any of the Harry Potter movies.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 49}, {"text": "Drink {int} times if you've ever spent more than , dollars in a day.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 50}, {"text": "Drink {int} times if your current partner is the best screw of your life Or you can just pretend, nobody will know the difference.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 51}, {"text": "Drink {int} times if an ex was the best fck you've ever had.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 52}, {"text": "Drink {int} times if you've ever played a video game for more than hours straight.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 53}, {"text": "Asshles who have stolen money from a relative drink {int} times.", "count": 1, "uses": 0, "rounds": 0, "personal": false, "remote": true, "unique": false, "id": 54}, {"text": "Drink {int} times if you have recently dreamt about something you can't even tell your best friend...", "count": 1, "uses": 0, "rounds": 0, "personal": fa
